version: '3'
services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "sa363975***!!!"
        MSSQL_PID: Express
    ports:
        - "1433:1433"
  customer-api:
    build:  .
    environment: 
        DBServer: "ms-sql-server"
    ports:
        - "8080:80"
